### ISSUE TITLE
Music Player Doesn't Work

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/technic#125]
The music player does not appear to work. I tried putting files called "technic_track1.ogg" as well as "technic_track1" into both the cache folder and the mod's folder itself. Looking at the code, it appears to try to concatenate a string and an int together to come up with the filename. While I don't have much Lua experience, I do wonder if that might be the problem.

**Comment by EmiXLabs** [comment]
@cheapie I'm adding technic_track1 and technic_track1.ogg to cache/media and cache/ folder, but its not playing. How you solved problem?

**Comment by cheapie** [comment]
Music is specified server-side, from what I can tell.

**Comment by EmiXLabs** [comment]
@cheapie I'm using my desktop computer as server, and as a server, which folders it will check for music files? Is there simple way for adding ogg files to music player (in server side)?
Thanks.

**Comment by cheapie** [comment]
The mod's texture folders, IIRC.
