### ISSUE TITLE
Use minetest.clear_craft to remove recipes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/technic#292]
Look at here:
https://github.com/minetest-technic/technic/blob/master/technic/crafts.lua#L166

Minetest has now the awesome function `minetest.clear_craft` to remove crafting recipes. It should be used everywhere instead of this little hack.

**Comment by MT-Modder** [comment]
:+1:

**Comment by VanessaE** [comment]
69feeef0afc0d66dd8809481c434ba0afa33600e

**Comment by DS-Minetest** [comment]
Hm, I think, I didn't get all override to 0 recipes eg. colors.
