### ISSUE TITLE
Constructor (mk1 mk2 mk3) get removed from world if facing up

### ISSUE THREAD

**Issue by expertmm** [minetest-mods/technic#328]
If you leave items in the inventory when you rotate it to point upward (using the screwdriver), it won't delete the constructor, but the constructor doesn't work. But, if you place items in the inventory after rotating it upward, the constructor will delete itself (and all the items) once powered.
Technic version: git 3/16/2017
Minetest server version: git 3/16/2017

**Comment by HybridDog** [comment]
∑M, the constructor only supports 4 directions: https://github.com/minetest-technic/technic/blob/master/technic/machines/other/constructor.lua#L91
see also: http://dev.minetest.net/minetest.facedir_to_dir

**Comment by HybridDog** [comment]
@VanessaE, why can the constructor only be used horizontally?

**Comment by VanessaE** [comment]
Because...that's how it was originally meant to be?  I try not to change existing behavior if I can help it, but if fixing something means reinforcing that behavior, not much else I can do.

**Comment by HybridDog** [comment]
l guess when the constructor was added, players couldn't rotate nodes yet, so 0-3 were sufficient.

**Comment by DS-Minetest** [comment]
Probably with the vertical constructor it will be like with the mesecons vertical movestones. No one is against it but everyone is too lazy to make it.

**Comment by numberZero** [comment]
@DS-Minetest 
> vertical movestones
> but everyone is too lazy to make it

not everyone. Our admin made that) 

On topic: it should support all directions just like other machines (breaker, deployer) do.
And yet another question: does it respect protection? I remember some time ago our admin fixed that on the server, but here it doesn’t seem to be fixed...

**Comment by HybridDog** [comment]
> And yet another question: does it respect protection?

It can't, mesecons signals don't carry player information.
Anyway, there're worse bugs, e.g. the item doubling itemframes bug in VanessaE's homedecor mod.

**Comment by numberZero** [comment]
@HybridDog but the breaker does that. It acts under the name of its placer.
