### ISSUE TITLE
Technic needs CPU-limiting

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/technic#330]
With large servers and complex builds, Technic has a tendency to push a server's CPU usage up pretty high, dragging its responsiveness down to unacceptable levels.

I don't know too well how Technic actually works, but some kind of "limiting" features are needed, i.e. checking the current dtime and skipping operations, limiting how often a machine will actually update, using timers where possible (if not already done), limiting how quickly a network re-calculation can take place (and limiting how much of a network actually needs it), things of that nature.

**Comment by numberZero** [comment]
Well, it’s possible to skip updates. But the actual Technic implementation seems to be very ineffective, it abuses the metadata, updating it several times per second in each and every connected machine. There should be a better way to make it work.

**Comment by HybridDog** [comment]
You could rework the machines to not update consistently but have a function with the passed time as argument, as side effect it makes them work in unloaded chunks and server lag doesn't mean longer furnace burntime or similar.
The metadata can be cached.
Also, l made a mod to spread heavy calculations over time. It successfully fixes long lag spikes which are annoying for the client.
https://github.com/HybridDog/function_delayer

**Comment by numberZero** [comment]
uh, that requires a lot of effort. Sadly I haven’t that much time now.

**Comment by LouisCyfer** [comment]
well .. technic is large and beautiful but you might just look out for minetest.register_globalstep(function(dtime)

sample:

> local timer = 0
minetest.register_globalstep(function(dtime)
		timer = timer + dtime
		if timer >= 0.2 then timer = 0 else return end
end

**Comment by VanessaE** [comment]
There is work in progress to fix Technic, so this issue is invalid now.
