### ISSUE TITLE
nuclear reactor core gap to cable

### ISSUE THREAD

**Issue by DS-Minetest** [minetest-mods/technic#342]
There's a gap between the nuclear reactor core and the connected cable:
![screenshot_20170402_172817](https://cloud.githubusercontent.com/assets/7613443/24589193/bb53b780-17d6-11e7-91a7-f88f887da54b.png)
I suggest making the core to a connected nodebox.
I will do this if no one else does and I've got time.

**Comment by VanessaE** [comment]
Don't bother altering the reactor model - I'm going to turn this into a proper mesh node soon anyway.

**Comment by DS-Minetest** [comment]
Ok, but please don't make it too round.
I suggest making it larger than one node since there's only water near and it could look nice. Perhaps it's a bad suggestion.
This issue should be closed when the nuclear reactor core gets  the new model or something like that happens.
