### ISSUE TITLE
a great idea for technic chests

### ISSUE THREAD

**Issue by StellaAnne** [minetest-mods/technic#349]
here's a great idea for technic chests:

there should be a button to dump all items in your inventory into the chest because it is such a pain to put stuff in one at a time.

**Comment by VanessaE** [comment]
I don't see that being especially useful since you can shift-click an item to move the whole stack (it takes only a few seconds to transfer one's entire inventory).  However, what WOULD be useful for testers or perhaps creative mode is a button that'll erase the chest's contents and fill it with stacks of some generic node like cobble or dirt.

**Comment by JamesTobin** [comment]
My point is what if I have like 75 stacks of something? Or have 75 non stackable items

**Comment by JamesTobin** [comment]
It takes approximately 1 minute to fill the chests manually

**Comment by VanessaE** [comment]
If you have 75 stacks, you surely have a larger inventory than 99% of Minetest players :smile: 

Anyway, it took me 9 seconds to transfer 32 stacks of stuff from my inventory to a chest.  That's fast enough.

**Comment by JamesTobin** [comment]
uh.. how do you do that???

**Comment by VanessaE** [comment]
Hold down shift and click on each item in my inventory and it's zapped right into the chest.  No drag-and-drop needed.

**Comment by JamesTobin** [comment]
cool, i didnt know that

**Comment by VanessaE** [comment]
All of this aside, if there's any place that such a button belongs, it isn't a chest but rather the inventory itself.  This might be a useful feature to add to Unified Inventory, if anything.

**Comment by JamesTobin** [comment]
are you also the developer of unified inventory?

**Comment by VanessaE** [comment]
I am not.  RealBadAngel was for both projects.  I contribute to that project though, from time to time.

**Comment by JamesTobin** [comment]
ok :)
