### ISSUE TITLE
Dark green wool craft getting corrupted by grinder_recipes use of clear_craft

### ISSUE THREAD

**Issue by mtango688** [minetest-mods/technic#370]
I'm not sure exactly what's going on, but if you remove the clear_craft in line 33, you can suddenly craft dark green wool (rather than just normal green wool when you try to craft wool + dark green dye).

**Comment by numberZero** [comment]
@mtango688 
probably unrelated to `technic`, sounds more like core bug; ask in https://github.com/minetest/minetest and don’t forget to mention exact MT version

**Comment by mtango688** [comment]
After looking into this, it does look like an engine issue. It may take some time to track down a reliable way to repeat this bug, though. I've tried different configurations, and the exact problem remains elusive.

**Comment by VanessaE** [comment]
This is a minetest engine or minetest_game bug, triggered partly by the default dye mod.\

Default wool mod is specifying white wool and any dye in the "basecolor_green" group should produce the brighter green wool, while "unicolor_dark_green" should produce the darker green wool.

The default dyes mod puts both green dyes in the "basecolor_green" group: https://github.com/minetest/minetest_game/blob/master/mods/dye/init.lua#L38-L39

The engine is probably just picking the wrong group of the two to match the recipe against.

**Comment by numberZero** [comment]
So, this is an MTG bug. The engine can’t know which group is more specific (that might be a useful feature, though), so is free to choose either.

**Comment by mtango688** [comment]
For future reference, I have reported this:

https://github.com/minetest/minetest/issues/5962

Basically, if you have Technic you will notice this problem (if you try to craft dark green wool with the minetest_game + just Technic and its dependencies).

**Comment by paramat** [comment]
We have simplified dye color groups in MTG:
https://github.com/minetest/minetest_game/commit/3484ff23add2855e0cea7c83004425b53778d8e4
https://github.com/minetest/minetest_game/commit/6f80fd3737cd4de30e548dd48bc0ab8c288d9930
This may fix the issue however changes may need to be made to technic.
