### ISSUE TITLE
Add support to Ethereal NG trees

### ISSUE THREAD

**Issue by DrHackberry** [minetest-mods/technic#375]
[Ethereal NG](https://github.com/tenplus1/ethereal) is a quite fantastic mod which adds a lot of things included biomes and trees, compatible with Moretrees. I usually use both mods and I noticed that Technic chainsaw does not support Ethereal NG trees. 
Would it be possible to add support to Ethereal NG ?

**Comment by cordial-cobra** [comment]
I agree that Ethereal is a fantastic mod. I did my own custom support for this when I was trying to use the chainsaw on the trees. I think that I added in the ability to cut all of plant life from the ethereal mod down using the chainsaw. I'm thinking of putting in a pull request on this but I'd like to know if this is actually something that is wanted before I do so.

**Comment by DrHackberry** [comment]
To my mind : adding support for Ethereal NG does not remove anything to anyone : players can still use chainsaw as they already do and it adds some logic : with Moretrees and Ethereal NG installed, you can cut all trees.

**Comment by cordial-cobra** [comment]
Yeah. I am (hopefully) getting to discussing this with some of the people who work on the engine itself. In the mean time, I plan on putting in the pull request with the code for it as early as tomorrow (a server I'm helping with uses both mods and I talked to the owner about this today).

**Comment by numberZero** [comment]
> if this is actually something that is wanted

Yes, I think; there are many mods supported already. But sadly people with push access rarely check PRs here...

> discussing this with some of the people who work on the engine itself

That doesn’t seem to be engine-related issue, what do you plan to discuss?

**Comment by cordial-cobra** [comment]
Whether or not support for ethereal being added to the chainsaw here is wanted or not.
-Mr_Pardison

**Comment by numberZero** [comment]
> Whether or not support for ethereal being added to the chainsaw here is wanted or not.

@VanessaE am I right that Ethereal (NG) support in Technic would be nice to have?

BTW, that has nothing to do with [the engine](https://github.com/minetest/minetest) itself, `technic` is a separate project.

**Comment by VanessaE** [comment]
It might be I suppose, however I've never used that project, so I'm not the one to ask. :smile:

**Comment by numberZero** [comment]
But there seems to be no one else to ask...

**Comment by VanessaE** [comment]
Sowwy :smile:

**Comment by Billre** [comment]
The chainsaw in technic needs work.   You can't just chop down one tree with it if its leaves touch another tree - it will also chop down that and other connected trees for as much power as the chainsaw holds.  This tends to grief tree stands like jungle trees.  I'm not comfortable with this unintuitive behavior being used on all trees.  On the other hand, ethereal trees (besides its version of jungle trees) don't seem to clump together much and it may not be an issue.

**Comment by cordial-cobra** [comment]
There are some instances of redwoods clumping together that I have seen but IMO these don't happen often enough to be much of an issue, especially if the area is unprotected.

**Comment by numberZero** [comment]
Such chainsaw behavior is really annoying. Especially as it **does not** respect protection (except of the node you click on). Oh well, I remember that large beautiful *wooden* spawn building...

Still, even for legitimate usage that makes it too easy to accidentally chop down a forest instead of a tree. But that’s not that easy to fix. #398

**Comment by cordial-cobra** [comment]
PR for this: #415

**Comment by gpcf** [comment]
also, chainsaw works pretty well in h-v-smacker/technic
