### ISSUE TITLE
sort_inventory destroys item metadata!

### ISSUE THREAD

**Issue by cx384** [minetest-mods/technic#381]
[`get_metadata()`](https://github.com/minetest-mods/technic/blob/master/technic_chests/register.lua#L137) is deprecated, because an item can have more then one metadata!
This issue is painful, because my [inventorybags mod](https://forum.minetest.net/viewtopic.php?f=11&t=17847) is using the metadata as item storage.

**Comment by cx384** [comment]
In addition you can accidentally make your keys unusable, because of this bug.

**Comment by Ekdohibs** [comment]
https://github.com/minetest-mods/technic/commit/930c51eef954d436e559b8b67b3c682d6c0865fb
