### ISSUE TITLE
Sulfur?

### ISSUE THREAD

**Issue by dpleshkov** [minetest-mods/technic#384]
I am using Minetest 0.4.16 with v7 map generation and I have a problem finding sulfur around the world. It seems to not be generated. Where can I find sulfur and under what depth is it generated?

**Comment by dpleshkov** [comment]
I also seem to have a problem finding a crafting recipe for concrete.

**Comment by DS-Minetest** [comment]
Sulfur is generated at some lava lakes.

Use a crafting guide (like the one from unified_inventory) to find the concrete recipe.

**Comment by soupfly** [comment]
Sulfur is very rare for a mineral used in the most basic recipes. I generated a new world in creative and explored the depths in noclip and found 10 lava lakes. Only one had sulfur deposits in it.

**Comment by benrob0329** [comment]
But that is countered by the fact that when you do find some, its a metric crapton and your basically set for life.

**Comment by SmallJoker** [comment]
Question is answered. When there's too less lava generated, it's a Minetest issue.

**Comment by reusityback** [comment]
MTG is in maintenance mode minetest/minetest_game#2710 and it's frustrating to not find lava after weeks of looking. Maybe I don't understand [how lava lakes are generated](https://wiki.minetest.net/Lava). 

There are mods like [Ethereal NG](https://content.minetest.net/packages/TenPlus1/ethereal/) that generate lava lakes and I wonder if technic_worldgen could support sulfur generation at Ethereal-generated lava lakes?

**Comment by SmallJoker** [comment]
@reusityback 

About Eternal NG: Add `minetest.register_on_mods_loaded(function()` + `end)` around the following registration function. Is sulfur now generated in *new* mapblocks?

https://github.com/minetest-mods/technic/blob/bce5306abea765fed1fdfeb775ed3abd21ff2863/technic_worldgen/oregen.lua#L151-L153

About regular lava: lava lakes [appear 256m below the water level](https://github.com/minetest/minetest/blob/master/src/mapgen/cavegen.cpp#L533-L537) (which is usually 0m, hence at -256m) . Although they could really appear more frequently. Here's one example:
![screenshot_20220912_134240](https://user-images.githubusercontent.com/1497498/189646641-44023b4a-1ebc-4f7e-a1f3-3dea202f98f9.png)
