### ISSUE TITLE
Extruder shape (wire) is consumed during processing

### ISSUE THREAD

**Issue by Azzyj** [minetest-mods/technic#394]
When making Glass Fiber (6028:32021), the extruder outputs 8 glass fiber & consumes the borosilicate glass bar as well as the Extruder Shape (6026:32356).

**Comment by DS-Minetest** [comment]
What are you writing about?¿?

**Comment by Azzyj** [comment]
The extruder EATS the plate (6026:32356) when you're trying to make glass fiber (6028:32021).

**Comment by VanessaE** [comment]
You must have this project mixed up with something else, @Azzyj.  There is no "glass fiber" or "fiberglass", nor any kind of "extruder", nor any kind of "plate" that would be associated with those things.

Furthermore, those numbers you gave have no meaning to this project.

**Comment by Azzyj** [comment]
My mistake, wrong repository.
