### ISSUE TITLE
Chainsaw digs entire forest instead of single tree

### ISSUE THREAD

**Issue by numberZero** [minetest-mods/technic#398]

**Comment by h-v-smacker** [comment]
Sometimes it's worse, it strips away the leaves from a whole grove, and then "oops, out of charge". I've seen plenty of such mutilated groves around.

**Comment by SmallJoker** [comment]
Fixed by radius limitation based on the distance to the clicked node.
https://github.com/minetest-mods/technic/blob/9b7c44b4530bf82790af495ac574a998656cade9/technic/tools/chainsaw.lua#L10-L11
