### ISSUE TITLE
It is impossible to produce bronze

### ISSUE THREAD

**Issue by nirasa1957** [minetest-mods/technic#400]
My Minetest version is 0.4.16. Mods: technic, technic_chest, technic worldgen and others (pipeworks, mesecons ...).
The bug is in technic_worldgen. The recipe of bronze ingot can not be seen and it can not be done.
(sorry for my english)

**Comment by numberZero** [comment]
Bronze is an alloy and should be made in the alloy furnace.

**Comment by nirasa1957** [comment]
The default recipe from Minetest is 8 copper ingots and one tin ingot = no tinkers mode. This is in / usr / share / minetest / games / minetest_game / mods / default / line 459-466. It works without tinkers_worldgen. If I allow the mod, it is impossible to create bronze from copper and tin ingots or the alloy furnace from copper dust and tin dust. Output is empty.

**Comment by numberZero** [comment]
Sorry, didn’t noticed they added tin in the MTG. You probably have `default:tin_ingot` instead of `moreores:tin_ingot` which `technic` uses. Try [this branch](https://github.com/numberZero/technic/tree/use-mtg-tin/) instead.
P.S. `technic_worldgen` doesn’t even mention tin nor bronze.

**Comment by nirasa1957** [comment]
Yes, alloy furnace works = from tin and copper dust = I have bronze. But default recipes from mtg not works (8 copper ingots, 1 tin ingots)

**Comment by numberZero** [comment]
> But default recipes from mtg not works (8 copper ingots, 1 tin ingots)

That’s intended.

**Comment by nirasa1957** [comment]
Aha. It's okay. Thanks.

**Comment by BobFred7** [comment]
Should this be closed?
