### ISSUE TITLE
Coal Dust requires Grinder; Grinder requires Coal Dust

### ISSUE THREAD

**Issue by dhausmig** [minetest-mods/technic#405]
I want to make a grinder but I do not have coal dust. To get coal dust I need a grinder. There must be a way to make Coal Dust without an LV Grinder or HV Grinder otherwise no machines can be made. Either a fuel powered grinder or a manually operated one would be acceptable. A crafting recipe would also enable bootstrapping technic.

**Comment by Ekdohibs** [comment]
A grinder can be made without coal dust. The cast iron required for the machine casing can be obtained by cooking wrought iron.

**Comment by VanessaE** [comment]
This question comes up a lot.

Using a normal, ordinary furnace, cook iron lumps to get wrought iron ingots (Technic's name for ordinary Minetest steel ingots), then cook those wrought iron ingots to get cast iron ingots.

Use bricks to make a fuel-fired alloy furnace, and use that to make brass ingots from copper and zinc ingots.

Use the brass and cast iron ingots to make machine casings.

Use one of thos along with other materials to make the machine you need.
