### ISSUE TITLE
Is Hydro LV giving now 1575 EU; i.e., 1.5k holycow

### ISSUE THREAD

**Issue by tanmayameher** [minetest-mods/technic#411]
I just downloaded the updated technic mod from here and tested it in singleplayer and saw something unusual.

LV hydro used to produce 150 as per my memory last i played. Now, it produces around 1575. Is it intentional or it is a typo?

I mean this would render all fuel fired furnace including HV ones  and the  LV Geothermal obsolete. lol :P Former is pretty difficult then the LV hydro. Latter stand no chance at 300 EU power  compared to LV hydro (current ones).

Please reply.
Thanks and regards,
TM

**Comment by VanessaE** [comment]
This is intentional, as the hydro turbine also requires running water (it used to work only in standing water), and this is a bit better balance against the others (which still need tuning a bit), using the nuke reactor as the benchmark.

**Comment by tanmayameher** [comment]
Ok. 👍 

Living in a city near a Dam; it was always awkward to me when hydro was giving low power in minetest. so 🥇

But, it is still in LV section. Shouldn't there be a HV hydro kind of thing. i mean they produce enormous power and they are almost major share of renewable energy right?! Some of them even producing more power than largest nuclear setups :P. Looking at [Source](https://en.wikipedia.org/wiki/Hydroelectricity) feels there is some injustice towards hydro electricity ;)

But it is what it is if you guys have settled down for this or thinking / progressing on more powerful things :)
Thanks and regards

**Comment by VanessaE** [comment]
That's exactly why I bumped it up.  We don't use wooden paddlewheel generators anymore :stuck_out_tongue_winking_eye: 

LV/MV/HV is just a naming thing in technic, it doesn't matter too much, but you're right that they ought not be LV at all.  To my mind, they ought to really be MV.  However, it's too late for that now.  The only way to solve that is to make a new MV turbine with a 1575 EU output, and make the LV ones 150-200 again.

**Comment by tanmayameher** [comment]
That would be cool and give a little more incentive to player, to pursue hydro too (upgrade to MV and stuff etc). Previously, they were neglecting it. But, now they are just making towers of hydro LV. Looks like water fountain all around map xD . Because, hydro setups are really big and not easy to setup; i guess. So, shouldn't be easy to make either :) So, yeah i am voting for tier system in hydro. May be i try coding it. Once tried, messed it up.

**Comment by tanmayameher** [comment]
VanessaE, I have made a MV hydro finally. Reduced the power of LV hydro to 175 EU (i.e., in between 150-200). The MV hydro is 10x more powerful (has 1750 EU). It's crafting recipe is not easy too :) or rather kind of upgrade so giving player more fun and survival aspect. 

Also, I had a nice texture (made by myself) for this machine which is used by a server admin (Gundul  from jungle server). So, i uploaded those. Hope you and other guys like it and give some review on it. Looking forward to generate a pull request and merge it :)

Thanks and regards

**Comment by numberZero** [comment]
@tanmayameher and where is the PR? ;) (BTW, don’t PR from master, use a dedicated branch instead).

**Comment by tanmayameher** [comment]
@numberZero yes. i will do a PR. That's what i was clarifying in my last paragraph. i was asking for a permission (kind of). It is not required to do a PR if you guys are not interested. right?! Seems now that you guys are interested. I will generate one. :) It may be my reclusive and hesitant behavior kicked in :blush:
