### ISSUE TITLE
Can't connect hydro genderators

### ISSUE THREAD

**Issue by ericblank** [minetest-mods/technic#416]
I have water flowing on them and the light changed to green, but I can't seem to connect the LV cable anywhere, top bottom side etc. What am I doing wrong?

**Comment by numberZero** [comment]
Green? What version are you using?

**Comment by ericblank** [comment]
I'd have to ask the admin. The top spins and the bottom turns green when water runs over it

On February 17, 2018 1:34:29 PM PST, Vitaliy <notifications@github.com> wrote:
>Green? What version are you using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest-mods/technic/issues/416#issuecomment-366473099

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by VanessaE** [comment]
That's a mesecons water turbine, which is little more than a water flow sensor.  It is NOT a power supply - you're thinking of technic's water mill (grey box with bluish "gears" on the sides and a red light on top).
