### ISSUE TITLE
Use treecapitator for the chainsaw

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/technic#427]
The [treecapitator](https://github.com/HybridDog/treecapitator) mod scans a tree and the surrounding trees and then digs the nodes which belong to the cut tree. It can easily be extended to capitate trees only with technic chainsaw.
In my opinion it can detect the trees' nodes a lot better than technic's chainsaw, that's the mod's purpose after all.

**Comment by SmallJoker** [comment]
You're welcome to open a PR if you think technic needs this. The current chainsaw does an okay-ish job, hence I wouldn't spend time on implementing this request.
