### ISSUE TITLE
Battery boxes can supply power from the side without losing charge

### ISSUE THREAD

**Issue by Hawk777** [minetest-mods/technic#439]
I built a simple network with a line of cable on the bottom and, with plenty of separation between them, an LV battery box, a switching station, and an LV grinder on top of the cable. Then I charged the battery box up a bit with an energy crystal. Then I put some ore in the grinder. The ore was ground, and the battery charge level went down. Perfect.

Then I removed the cable under the battery and put some more ore in the grinder. Nothing happened, because the grinder was unpowered. Perfect.

Finally, I put some cable *beside* the battery instead of *below* it, connected to the network. The grinder started working and ground the ore, even though the hover comment for the battery box said it had no network. When I reattached cable on the bottom afterwards, I discovered that the charge level on the battery had not gone down at all; the energy came from nowhere.

This was on 9b40d02fbd9e8c39c5c64cc7de89a7fe45382f04.

**Comment by SmallJoker** [comment]
Reproduced this bug locally with the current HEAD and 930c51e. This bug seems to be present for a much longer time already.

**Comment by numberZero** [comment]
The whole network management needs rewrite. There was an attempt in #380, but it doesn't seem to succeed.
