### ISSUE TITLE
LV battery box formspec charge meter doesn’t work

### ISSUE THREAD

**Issue by Hawk777** [minetest-mods/technic#440]
All battery boxes have a charge meter in their formspecs on the left side, labelled “Power level”. For the MV and HV battery boxes, the meter works fine. For the LV battery boxes, the meter always reads empty, regardless of the charge level of the box. The hover text and node texture show the proper charge level, and the battery box properly stores and release energy; only the meter is broken.

This happened on 9b40d02fbd9e8c39c5c64cc7de89a7fe45382f04.

**Comment by Xiong** [comment]
Confirmed.

**Comment by DS-Minetest** [comment]
This should be easy to fix.
The problem lies here:
https://github.com/minetest-mods/technic/blob/d1b54a573c6287ea1d63b9c3f979c39058b1331a/technic/machines/register/battery_box.lua#L131-L136
