### ISSUE TITLE
Grinder required to construct a Grinder

### ISSUE THREAD

**Issue by cyisfor** [minetest-mods/technic#474]
* You can't use a grinder without a switching station. 
* A switching station requires a LV transformer to construct. 
* A LV transformer requires rubber fiber. 
* Rubber fiber requires coal dust. 
* Coal dust can only be produced with a grinder.

Constructing an LV transformer has required rubber since March of 2016, so... nobody has ever tried to use technic outside of creative mode for the past 2 or 3 years? Because unless I'm missing something, it's completely unusable.

**Comment by VanessaE** [comment]
Maybe your copy of Technic is modified somehow, but you're missing one detail: it relies on mesecons fiber, not rubber fiber.  So this crafting chain works:

7 plastic -> empty spools
1 copper ingot + two empty spools -> spools of copper wire
4 spools of copper wire + 4 steel ingot -> copper coil (you get the empty spools back)
1 sapling or 1 raw latex -> cooking -> glue
glue -> cooking -> Mesecons fiber

2 copper coil + 5 steel ingot + 2 Mesecons fiber -> LV transformer

steel ingot -> cooking -> cast iron ingot
8 brick blocks -> fuel fired alloy furnace
2 copper ingot + 1 zinc ingot -> alloying -> brass ingots
1 brass ingot + 8 cast iron ingots -> machine casing

6 paper + 3 copper ingots -> LV cables

2 copper ingot + 1 LV transformer + 1 machine casing + 3 LV cable -> switching station

**Comment by BobFred7** [comment]
Should we close this?

**Comment by BobFred7** [comment]
Hold on: https://github.com/minetest-mods/technic/blob/master/technic/crafts.lua#L106
The transformer recipe (shortly after that line) uses an item that is a choice between mesecons fiber (what most technic installations use, and what VE thinks is correct) and technic rubber fiber (what cysifor is having a problem with). Cysifor's problem occurs whenever you are using technic without mesecons_materials.

**Comment by TechDudie** [comment]
Maybe mesecons_materials should be a dependency.

**Comment by SmallJoker** [comment]
#578 merged
