### ISSUE TITLE
Bad Chest Formspec

### ISSUE THREAD

**Issue by Xiong** [minetest-mods/technic#478]
Also please see #477

![Gold Locked Chest](https://i.imgur.com/cXhL1bg.png)

Thought I'd get used to this but I was wrong. The itty-bitty elements are bad; the no-contrast background is worse. My eyes hurt. 

Recently the gold chest formspec filled my tiny screen... an iota away from disaster but fine. The elements were just barely large enough to touch. The gray is such a good idea I even thought of it myself... but no. Too many blocks are gray or nearly so. 

Please! This was okay:

![Wooden Locked Chest](https://i.imgur.com/QH5woWx.png)

**Comment by FriendlyGamer** [comment]
I agree, this is insane! It doesn't scale at all if you scale the UI beyond a like maybe 10% or so larger.  

An alternative? Why not make it so you get multiple pages or scroll able?

**Comment by louisroyer** [comment]
Do you still have this issue?

What I have by default on gold chests (and silver chests):
![2020-08-13-153034_978x736_scrot](https://user-images.githubusercontent.com/55180044/90141475-7319ad80-dd7b-11ea-99b0-0cc6e117067e.png)

New disposition proposal to avoid overlapping(not implemented; image edition with gimp):
![2020-08-13-153034_978x736_scrot_proposal](https://user-images.githubusercontent.com/55180044/90141310-482f5980-dd7b-11ea-8bed-c7b7a0d9ff8c.png)

or we could add a configuration tab with all config buttons and only keep the inventory, the sort button, and the name (but not the edit button) on the main tab.

**Comment by Emojigit** [comment]
My suggestion (also GIMP edited):
![suggest_technic_glod_chest](https://user-images.githubusercontent.com/55009343/122640634-3523ad80-d133-11eb-8af7-3525a3438bbd.png)
[suggest_technic_glod_chest.xcf.zip](https://github.com/minetest-mods/technic/files/6680574/suggest_technic_glod_chest.xcf.zip)

**Comment by auouymous** [comment]
Moving to the side is great for english but could cause issues for translations with wider buttons. A config tab or button that opens a new window would be perfect, but the chest's uneditable name should remain on the main formspec.
