### ISSUE TITLE
Lua controller overheats when GETing digilines data from a switching station

### ISSUE THREAD

**Issue by ghost** [minetest-mods/technic#486]
_I’m not sure where to place this but since the Lua controller does not behave like this on other events or on other Digiline events but only in conjunction with the switching station I’m putting this here._

I have a switching station providing 10.8 kEU MV energy, I connected the switching station to a Lua controller with a digiline (the switching stations channel is `mv`). The following super simple program is set up in the controller:

```lua
print('start')
digiline_send('mv', 'get')
print(event.msg)
print('end')
```

I expect something like …

```lua
"start"
{
	demand = 10000,
	supply = 10800
}
"end"
```

… when hitting "Execute". But the message gets repeated multiple times and the Lua controller overheats. [See log file of the result](https://github.com/minetest-mods/technic/files/2823450/log.txt).

Minetest on 0.4.17.1 and Digilines, Mesecons, and Technic on latest versions available.

**Comment by thomasrudin** [comment]
You seem to run in an endless send() loop there.
Messages should be checked in an event-handler:
```lua
-- click on "execute"
if event.type == "program" then
 digiline_send("mv", "get")
end

-- event from switching station
if event.type == "digiline" then
 print(event.msg)
end
```

**Comment by Linuxdirk** [comment]
Thanks, I think I can work with this. So it’s just a misunderstanding … Any idea how I can get this into a loop querying multiple switching stations and do something with the return values?

**Comment by BuckarooBanzay** [comment]
@SmallJoker this can be closed too (sorry for the pings)
