### ISSUE TITLE
[solved] cant use newer technic downloads (upgrade)

### ISSUE THREAD

**Issue by Minetest-One** [minetest-mods/technic#490]
I use still a download from end feb 2018, is running also under 5.1.0-dev

So I download an version a week ago and the lastest on 12.03.2019, 
- and just cut the old technic folder out of mods, 
- and copied the new extracted short-named "technic" folder in.
No changes in .mt (technic = true) or anything else, BUT

In both cases it is not loading, but even not telling not found - is there any minor change ?

**Comment by DS-Minetest** [comment]
Have you tried to start your world twice in a row in one minetest session? It doesn't print the error messages into chat at first time that you start world after starting minetest.

**Comment by HybridDog** [comment]
You can write /mods in minetest chat to see which mods are installed.
Maybe technic has new dependencies, have you looked at Configure in the main menu yet?

**Comment by DS-Minetest** [comment]
>Maybe technic has new dependencies.

Indeed, it has:
https://github.com/minetest-mods/technic/blob/700faca5cb9068f2a71cf60e51dfeea57cf5bc6b/technic/depends.txt#L4

**Comment by Minetest-One** [comment]
ok, but shouldn't technic then report a missing dependency during start missed, and will not run like I remember it was with other Mods ?
I go to check - test and report here, what happen ...
