### ISSUE TITLE
Feature request: Realistic transmission cables

### ISSUE THREAD

**Issue by za267** [minetest-mods/technic#492]
Hi there, I'm interesting in working on an addition for this mod which would essentially be a modified hv_cable for use with high voltage transmission pylons... used for long distances.  I've built transmission pylons on my map but the hv_cables just doesn't work nicely with it.  The appearance is not very realistic.  I'm hoping to make an hv_cable which has the texture of either one or two metallic cables.  It could act almost exactly like an hv_cable...
Since I don't want to start working on this unnecessarily, feedback would be appreciated :)

Here is an example of a pylon with a standard_hv cable... I'll try to make a mockup later of what it might look like instead.

![screenshot_20190321_114521](https://user-images.githubusercontent.com/2365202/54764892-f35fd180-4bce-11e9-9e4d-754c553d8281.png)

**Comment by VanessaE** [comment]
Given the sheer scale, the best thing to do would be to just run one HV cable and one or two MV cables (depending if you want a two- or three-conductor setup; I don't know much about power transmission), and hooking up only the HV one to anything live.  Cables not connected to an active network are completely inert, regardless of voltage or length - technic doesn't look at them unless there's a switching station connected.

**Comment by za267** [comment]
Thanks for the feedback... I might create a separate mod entirely then that would simply add a cable node... Maybe I'll bug you about it on IRC :)
