### ISSUE TITLE
technic_hydro_turbine_*.png cause warnings

### ISSUE THREAD

**Issue by ghost** [minetest-mods/technic#494]
The technic_hydro_turbine_*.png textures have been saved with interlacing and that's causing run-time warnings. Please re-save them without interlacing, which doesn't make sense in Minetest or for such small textures.

**Comment by BuckarooBanzay** [comment]
@SmallJoker this is fixed in https://github.com/minetest-mods/technic/commit/62fdb853ece2499b6a97a33a382c242b04534d7c and can be closed
