### ISSUE TITLE
NonContained Lag Issue (Jamming of Effectors like the Injectors and Node Breaker)

### ISSUE THREAD

**Issue by FriendlyGamer** [minetest-mods/technic#519]
Simply as the title. If you do for instance cobble generator>node breaker>chest and make the chest full (or wait until it is) then the server will take a considerate load. Due the "jamming" of in this case the node breaker.  

I am probably assuming this happens with other similar blocks. Why not just either "jam" the block itself so it doesn't "work" until the "jam" is cleared OR just delete the internal item(s) per cycle?

**Comment by BuckarooBanzay** [comment]
@SmallJoker this can be closed, its a `pipeworks` issue
@FriendlyGamer the item transport is handled by the `pipeworks` mod, even if you place the machines next to each other. There are settings to prevent some lag-scenarios: https://gitlab.com/VanessaE/pipeworks
