### ISSUE TITLE
ERROR[Main]: generateImage(): Could not load image "steel_strut_overlay.png" while building texture; Creating a dummy image

### ISSUE THREAD

**Issue by adrido** [minetest-mods/technic#524]
https://github.com/minetest-mods/technic/blob/76a39e71b9f81531e14efd7ec1b0accfefa0fa66/extranodes/init.lua#L145

shouldn't it be technic_steel_strut_overlay.png ? 
https://github.com/minetest-mods/technic/tree/76a39e71b9f81531e14efd7ec1b0accfefa0fa66/extranodes/textures

**Comment by fgrosswig** [comment]
your right, changed it to fix loading png.

`{ name = "strut.png^technic_steel_strut_overlay.png", color = "white" },`

they should make a patch out of it.

**Comment by BuckarooBanzay** [comment]
@SmallJoker this is fixed with https://github.com/minetest-mods/technic/commit/7696546d4710ab28e55abd7cde05c1dbcd39cf44 and can be closed

**Comment by SmallJoker** [comment]
Thanks.
