### ISSUE TITLE
Some recipes do not appear in built-in v5.4.0 crafting guide

### ISSUE THREAD

**Issue by jonathancutting** [minetest-mods/technic#585]
Some items in Technic either show no recipes, circular recipes, or uncraftable recipes in the new, built-in craft guide in Minetest 5.4.0. For example, the following items are uncraftable due to either circular recipes, recipes containing items that cannot be mined, crafted, or harvested, or no recipes...
- Carbon plate
- Composite plate
- Brass ingot
- Stainless steel ingot
- Carbon steel ingot

Technic and all required dependencies are up-to-date as of 10 Apr 2021. To reproduce issue, go to the default crafting guide (not the Crafting Guide mod) in the inventory in Minetest client v5.4.0, and view the crafting recipes for any of the items listed above.

**Comment by jonathancutting** [comment]
I've not spent much time learning Lua, but it looks similar to other object-oriented languages, so I've been looking through the code to see if I can diagnose the problem here. I found this in /technic/crafts.lua.
```Lua
 4 -- Remove some recipes
 5 -- Bronze
 6 minetest.clear_craft({
 7     type = "shapeless",
 8     output = "default:bronze_ingot"
 9 })
10 -- Restore recipe for bronze block to ingots
11 minetest.register_craft({
12     output = "default:bronze_ingot 9",
13     recipe = {
14         {"default:bronzeblock"}
15     }
16 })
```
If I understand this correctly, it removes any existing recipes for the bronze ingot, and replaces it with a recipe that just has a bronze block. I don't want to edit the code myself and do a `git push`, since I'm not well-versed in the language (and I don't want to break anything). However, would this restore the original recipe for a bronze ingot, if I rewrote lines 13 through 15 like this?
```Lua
recipe = {
    {"default:bronzeblock"}
},
{
    {'default:copper_ingot', 'default:copper_ingot', 'default:copper_ingot'},
    {'default:copper_ingot', 'default:tin_ingot', 'default:copper_ingot'},
    {'default:copper_ingot', 'default:copper_ingot', 'default:copper_ingot'}
}
```
Also, I notice some of the recipes in craft.lua use double quotes and some use single quotes. Which is the correct syntax, and could this be breaking things?

**Comment by auouymous** [comment]
The missing recipes are created with machines, perhaps the default craft guide can't display them, or maybe technic must support every craft guide.

The bronze recipe removes any existing simpler recipes and later adds a more complex recipe. Put 7 copper ingots and 1 tin ingot in an alloy furnace to get 8 bronze ingots. Or you can comment out lines 6 to 16 to restore any existing recipes.

The quotes don't break anything, they can both be used.

**Comment by jonathancutting** [comment]
Aha! I did not know this. I thought it was a bug, but it's by design. Good to know. Do you have any suggestions for a better craft guide that might show these Technic recipes? I'll close this bug report once I have an alternative one working.

**Comment by auouymous** [comment]
The machine recipes work fine in the `unified inventory` mod. There is another issue to support i3 and a PR for the craftguide mod. So it might be better to leave this issue open and rename to "Add compatibility with built-in v5.4.0 crafting guide".

**Comment by S-S-X** [comment]
Some recipes do not work well with any of supported crafting guides and this is because recipes cannot display multiple outputs, these recipes are actively skipped when registering recipes for crafting guides.

**Comment by jonathancutting** [comment]
I installed `Unified Inventory`, and that seems to display the missing recipes I was looking for. As for @S-S-X's issue, I'm not sure I follow... In any case, should I close this issue or rename it as suggested by @auouymous?

**Comment by S-S-X** [comment]
> I installed `Unified Inventory`, and that seems to display the missing recipes I was looking for. As for @S-S-X's issue, I'm not sure I follow... In any case, should I close this issue or rename it as suggested by @auouymous?

That was just note about additional actively skipped recipes, I mean there's multiple issues with many different recipe types not showing up and multiple causes for those. Not just some single specific problem with some specific recipes.

Yes it could maybe be better to have multiple bit more specific missing recipe issues for all these.

**Comment by Sharpik** [comment]
Hi, this mod should support even I3 recipes guide as do this commit:
https://git.minetest.org/RealBadAngel/technic/commit/1c219487d3f4dd03c01ff9aa1f298c7c18c7e189?style=split&whitespace=ignore-change

**Comment by SmallJoker** [comment]
Technic uses custom crafting recipes which cannot be represented with `minetest.register_craft`. If a craft guide does not show Technic recipes but has an API to register them for display, please open an issue or (preferably) a PR to add support for that guide to technic.

**Comment by limitedAtonement** [comment]
Users of my server were unable to craft bronze after introducing technic. Unfortunately, this wasn't noticed for a while, so we didn't think about technic introducing this issue. Luatic in IRC was able to help debug the removed bronze recipe in technic crafting module. I post this as a reminder that the missing bronze recipe in crafting guides results in an awful user experience. Thank you for the hard work and this interesting mod!

**Comment by SmallJoker** [comment]
@limitedAtonement Which craft guide where you using? I could have a look at implementing support for it, if that's possible with its provided API.

**Comment by limitedAtonement** [comment]
https://github.com/minetest-mods/craftguide. Looks like it's archived, so maybe I should be using something else?

**Comment by SmallJoker** [comment]
@limitedAtonement It turns out these registrations were broken since their introduction (1c219487d3f).
Fixed as of 455092e. Thanks for reporting.

**Comment by limitedAtonement** [comment]
@SmallJoker Wow, you're the best! I see the recipe now:

![image](https://github.com/user-attachments/assets/7866696f-9c53-4dd7-a4a3-4ac6c4acf5b8)

It doesn't say that I need to smelt, but this is way better now! When I look at "usages" of tin, I don't see bronze:

![image](https://github.com/user-attachments/assets/858f7c10-edff-4067-a8f1-789b42a56be4)

![image](https://github.com/user-attachments/assets/eb29b6f3-2e73-4335-b06b-ab3607e248f0)

Also, I must be using another crafting guide? Because when I view my inventory, then go to the next tab (Recipes), it doesn't show:

![image](https://github.com/user-attachments/assets/7a52c1c9-4a01-4a8b-a643-b0d0c41af7b3)

![image](https://github.com/user-attachments/assets/19f011ed-b96b-460a-bc70-dca0258902b7)

**Comment by SmallJoker** [comment]
@limitedAtonement That's [`mtg_craftrecipe` from Minetest Game](https://github.com/minetest/minetest_game/blob/master/mods/mtg_craftguide/init.lua). Please open a new issue to request support for this mod. From what I can see, it does yet not offer any API to register custom recipes.
