### ISSUE TITLE
Make playable with Mineclone2?

### ISSUE THREAD

**Issue by spacekookie** [minetest-mods/technic#594]
Hey! I'm pretty new to minetest games/ mods but: I play mineclone2 to have some survival mechanics (I find minetest game to be a bit boring).
Anyway, this mod seems to _depend_ on minetest game directly. Is this something that can be changed?

**Comment by SmallJoker** [comment]
No. There are simply too many references to `default`. However, a PR is surely welcome.

Good compatibility example: https://github.com/mt-mods/pipeworks/blob/master/crafts.lua#L1
