### ISSUE TITLE
Translation is not being displayed

### ISSUE THREAD

**Issue by reusityback** [minetest-mods/technic#595]
Nodes of technic_worldgen (marble, probably more) aren't being translated into German ("Marmor"). While technic_worldgen/locale/de.txt is there, in-game the translation doesn't work.

Some years ago there were #101, #103 and #104, but I don't understand the code enough to spot anything, [6d31965](https://github.com/minetest-mods/technic/commit/6d31965b36b40da472b666d01db774c79fb4ab47) and node descriptions in technic_worldgen/nodes.lua don't seem that different to me.

**Comment by auouymous** [comment]
Do you have the intllib mod installed?

**Comment by reusityback** [comment]
That solved it. Thank you!
