### ISSUE TITLE
Minor issue causing warnings in MT 5.5.0 with texture alpha clipping

### ISSUE THREAD

**Issue by Baigle** [minetest-mods/technic#597]
Posting because I have thousands of messages in my debug.txt about these, and I now see them after I allowed warning-level messages in chat. It won't be an issue until they require it to be set in the future.

> WARNING[Main]:   This warning can be a false-positive if unused pixels in the texture are transparent. However if it is meant to be transparent, you *MUST* update the nodedef and set use_texture_alpha = "clip"! This compatibility code will be removed in a few releases.

The affected textures are: 

> "default_leaves.png" of default:leaves_technic_cnc_cylinder
"default_leaves.png" of default:leaves_technic_cnc_cylinder_horizontal
"default_leaves.png" of default:leaves_technic_cnc_element_cross_double
"default_leaves.png" of default:leaves_technic_cnc_element_cross
"default_leaves.png" of default:leaves_technic_cnc_element_edge_double
"default_leaves.png" of default:leaves_technic_cnc_element_edge
"default_leaves.png" of default:leaves_technic_cnc_element_end_double
"default_leaves.png" of default:leaves_technic_cnc_element_end
"default_leaves.png" of default:leaves_technic_cnc_element_straight_double
"default_leaves.png" of default:leaves_technic_cnc_element_straight
"default_leaves.png" of default:leaves_technic_cnc_element_t_double
"default_leaves.png" of default:leaves_technic_cnc_element_t
"default_leaves.png" of default:leaves_technic_cnc_oblate_spheroid
"default_leaves.png" of default:leaves_technic_cnc_onecurvededge
"default_leaves.png" of default:leaves_technic_cnc_pyramid
"default_leaves.png" of default:leaves_technic_cnc_slope_edge
"default_leaves.png" of default:leaves_technic_cnc_slope_edge_upsdown
"default_leaves.png" of default:leaves_technic_cnc_slope
"default_leaves.png" of default:leaves_technic_cnc_slope_inner_edge
"default_leaves.png" of default:leaves_technic_cnc_slope_inner_edge_upsdown
"default_leaves.png" of default:leaves_technic_cnc_slope_lying
"default_leaves.png" of default:leaves_technic_cnc_slope_upsdown
"default_leaves.png" of default:leaves_technic_cnc_sphere
"default_leaves.png" of default:leaves_technic_cnc_spike
"default_leaves.png" of default:leaves_technic_cnc_stick
"default_leaves.png" of default:leaves_technic_cnc_twocurvededge

Thank you for your time, fixing this may not be as easy as imagined, based on comments by wsor and S-S-X on another mod about Warning spam.

**Comment by SmallJoker** [comment]
349676f
