### ISSUE TITLE
Mining drill does not work

### ISSUE THREAD

**Issue by alerikaisattera** [minetest-mods/technic#602]
**Bug description**

After recent update, mining drill does not work: it does not mine any blocks when used but consumes energy

**Steps to reproduce this issue**

Use mining drill on any block

**Comment by alerikaisattera** [comment]
This bug is introduced in https://github.com/minetest-mods/technic/commit/0f6bdb1bde5f476b8e4500cba559f813cd5276a1 . Replacing mining_drill.lua with older version fixes the issue

**Comment by alerikaisattera** [comment]
Seems to be caused by meta.mode not being available for Mining drill mk1

**Comment by SmallJoker** [comment]
@alerikaisattera Found this issue "by accident". I am sorry for this mistake. Feel free to ping me in such cases.

Fixed in bce5306
