### ISSUE TITLE
Unable to pull charged items out of an MV Battery Box

### ISSUE THREAD

**Issue by Bituvo** [minetest-mods/technic#606]
With Pipeworks, I can easily put an item into the charge slot. However, there is no way to get it out. Using filter-injectors on all the sides of the battery box does nothing.

**Comment by auouymous** [comment]
A `control logic unit` in one of the two bottom slots will automatically eject items into an adjacent pipe or inventory after charging. The ejection side depends on the direction the battery is facing, right if NS, left if WE.
