### ISSUE TITLE
Battery Boxes don't work anymore behind Supply Converters

### ISSUE THREAD

**Issue by debagos** [minetest-mods/technic#611]
After https://github.com/minetest-mods/technic/commit/718a5beda197cd0a775fd41aedfb5b1bbd5d1d8b Battery Boxes don't work anymore when they are behind a Supply Converter.

**Comment by auouymous** [comment]
#577 even mentions they don't work...

**Comment by SmallJoker** [comment]
This does seem less of a problem compared to the previously wasted energy (supply surplus). I think this problem can be solved too by writing `BA_eu_demand` into the switching station metadata and using that as well for the power calculations.

I will have a look at this.

**Comment by debagos** [comment]
I added the patch and the battery boxes do work again, even without replacing them.
Good job, thank you @SmallJoker for the quick response and fix!
Should problems arise with that patch, then I'll report them here.

**Comment by SmallJoker** [comment]
705961e

Thank you. Feel free to leave a comment here if there's any issue with it. I will then reopen the issue.
