### ISSUE TITLE
 Battery box does not see network related to issue #614

### ISSUE THREAD

**Issue by ulamthelucky** [minetest-mods/technic#615]
Issue #614 is fixed, however found a weird reproducible anomaly that is related.

Build a LV network (only tested LV)  with a power source (such as solar array),  a switching station. Then extend the LV cable out a few blocks out, or simply around a 90 degree bend. and put the battery box on the LV wire at the end.  It is not registered on the network.

Place a 2nd battery box next to the switching station or the solar array, and suddenly both battery boxes 'see' the network.

First battery box placed:

![image](https://user-images.githubusercontent.com/299530/204071463-99335382-c470-4044-9559-ae56a0291373.png)

After placing a 2nd battery box:

![image](https://user-images.githubusercontent.com/299530/204071497-052e71f5-285e-4731-b7d7-e5f68c3ac521.png)

Can even place many battery boxes, but if none are next to something they are not registered.

![image](https://user-images.githubusercontent.com/299530/204071568-b0ab3b70-fa4a-4c45-a3ab-4456a2859000.png)

But, add just a single anything else such as a solar array next to any 1 of the un registered boxes, and suddenly all are registered.
![image](https://user-images.githubusercontent.com/299530/204071619-ea5ad553-0ffa-45ee-b037-a94aeb023258.png)

One can even remove the node that (in this example the 2nd solar array) and the boxes remain registered.  Bug only occurs on initial placement of the battery box.    
  

    

**Steps to reproduce this issue**

**Comment by SmallJoker** [comment]
I thought you said it worked....

Actually this is my bad. Forgot to update the other function too (the duplication should not exist in first place). 21e0444

**Comment by ulamthelucky** [comment]
Works now.    Thanks!
