### ISSUE TITLE
No concrete 'moreblocks'

### ISSUE THREAD

**Issue by Adaemonium** [minetest-mods/technic#616]
The latest update doesn't have concrete moreblocks available despite various concrete slopes being shown in the craft guide. Only the concrete block can be found, as well as the concrete post and platform. Blast resistant concrete has all of its moreblock variants.

Minetest 5.6.1 (Windows), am using Unified Inventory, and updated technic via client. Node based mods in use are basic materials and items, factory bridges, mesecons, moreblocks, scifi nodes, technic and travelnet.

**Comment by SmallJoker** [comment]
There are no recent changes related to node registrations. Please run `git bisect` to find out which commit is responsible for this change.

**Comment by SmallJoker** [comment]
No answer in many months, hence closing.

@Adaemonium If this issue is still relevant please elaborate the problem further. Concrete is now part of `basic_materials`, does show up in Inventory Inventory, is craftable and does work in the moreblocks circular saw.
