### ISSUE TITLE
chainsaw triggers a on_mods_loaded() error

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest-mods/technic#620]
i had to disable the chainsaw lua by commenting it out.

I always got the following error:

> 2023-08-03 00:59:54: ERROR[Main]: ModError: Runtime error from mod 'technic' in callback on_mods_loaded(): invalid key to 'next'
> 2023-08-03 00:59:54: ERROR[Main]: stack traceback:
> 2023-08-03 00:59:54: ERROR[Main]:       [C]: ?
> 2023-08-03 00:59:54: ERROR[Main]:       [C]: in function '(for generator)'
> 2023-08-03 00:59:54: ERROR[Main]:       ...reative/worldmods/technic/technic/tools/chainsaw.lua:80: in function '?'
> 2023-08-03 00:59:54: ERROR[Main]:       .../ubuntu/minetest570/bin/../builtin/game/register.lua:446: in function <.../ubuntu/minetest570/bin/../builtin/game/register.lua:432>

The problem only started appearing recently, after the server restarted once

what could solve the problem?

**Comment by SmallJoker** [comment]
I see. There might be iterator issues when the table is modified while iterating. Fixed as of 45eae5b.

**Comment by MidnightPhantom** [comment]
Hey, SmallJoker I've also got an issue with the chainsaw, I've opened an issue so please could you check it.

https://github.com/minetest-mods/technic/issues/619
Here is the link
