### ISSUE TITLE
It is impossible to build a nuclear reactor

### ISSUE THREAD

**Issue by SUNsung** [minetest-mods/technic#629]
I'm trying to build a reactor and it keeps telling me: "the power plant seems to be built incorrectly".

The first assembly followed these instructions: https://mt-builder.neocities.org/nuclreact

After many unsuccessful attempts (I even tried a clean world with one mod installed), I finally decided to read the documentation.
I didn’t find any errors, but I tried using lead instead of stainless steel. (as I later noticed when trying to start the reactor, all the stainless steel itself changes to lead)

In this mod, everything works for me except the nuclear reactor((

**Comment by SmallJoker** [comment]
I did follow the same instructions and on my side it works well:

![reactor](https://github.com/minetest-mods/technic/assets/1497498/e5b96d45-10e6-4986-9864-7b51a6387453)

Have you yet ticked the checkbox "automatic start"? Otherwise it might not start due to missing blocks in its shell.

**Comment by BuckarooBanzay** [comment]
> The first assembly followed these instructions: https://mt-builder.neocities.org/nuclreact

you might have better luck with lead instead of stainless steel:

https://github.com/minetest-mods/technic/blob/410e341da5156cdcd8b031dfd7be13c723a095af/technic/machines/HV/nuclear_reactor.lua#L106-L121

**Comment by SmallJoker** [comment]
In fact I used stainless steel for my build.

**Comment by SmallJoker** [comment]
@SUNsung Due to lack of response within almost a year, I assume that the problem is resolved.
If you still cannot get it to work with the explanations provided above, please let me know.
