### ISSUE TITLE
Chainsaw does not work on dfcaverns' Tunnel Tube

### ISSUE THREAD

**Issue by alerikaisattera** [minetest-mods/technic#646]
Chainsaw does not work on Tunnel Tube trees from dfcaverns mod

When trying to cut down a Tunnel Tube tree from dfcaverns mod, nothing happens

**Comment by SmallJoker** [comment]
Please retry with the setting `technic_safe_chainsaw = true`. This was introduced because some trees are placed with `param2 != 0`, which is by default used to avoid cutting buildings.

**Comment by alerikaisattera** [comment]
It works with that setting changed. Probably I should close this

**Comment by TangentFoxy** [comment]
Where is this setting able to be modified? In the server's `minetest.conf`?

**Comment by SmallJoker** [comment]
@TangentFoxy Yes. As for clients (and thus local servers), the setting can be found in the main menu settings as well.
https://github.com/minetest-mods/technic/blob/master/settingtypes.txt
